# ################################
# Model: VGG2 + LSTM + time pooling
# Augmentation: TimeDomainSpecAugment
# Additions: 2D pooling
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1212
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/ASR_domain_TTS_dev_test_real_mix_2_BiLSTM/<seed>/<output_neurons>
wer_file: !ref <output_folder>/wer_TTS_RNN.txt
cer_file_test: !ref <output_folder>/cer_TTS_RNN.txt
ctc_file_test: !ref <output_folder>/ctc_TTS_RNN.txt
coer_file_test: !ref <output_folder>/coer_TTS_RNN.txt
cver_file_test: !ref <output_folder>/cver_TTS_RNN.txt
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# URL for the biggest LeBenchmark wav2vec french.
wav2vec2_hub: LeBenchmark/wav2vec2-FR-7K-large 


data_folder: /data/coros1/acaubriere/data/data_quaero/  # e.g, /localscratch/cv-corpus-5.1-2020-06-22/fr
accented_letters: True
language: fr # use 'it' for Italian, 'rw' for Kinyarwanda, 'en' for english
train_csv: !ref <data_folder>/TTS_emb.csv 
valid_csv: !ref <data_folder>/file_csv_quaero_test_Real_80_emb.csv
test_csv: !ref <data_folder>/file_csv_quaero_evaluatio_10h_Real_80_emb_ASR.csv

# longer sentences certainly correspond to "open microphones".
avoid_if_longer_than: 80.0
avoid_if_smaller_than: 0.5 

# Training parameters
number_of_epochs: 30
lr: 0.0001
lr_wav2vec: 0.0001

ctc_weight: 0.2
sorting: descending

# With data_parallel batch_size is split into N jobs
# With DDP batch_size is multiplied by N jobs
# Must be 6 per GPU to fit 16GB of VRAM
batch_size: 4
test_batch_size: 2

dataloader_options:
    batch_size: !ref <batch_size>
    num_workers: 2 
test_dataloader_options:
    batch_size: !ref <test_batch_size>
    num_workers: 2 

# BPE parameters
token_type: unigram  # ["unigram", "bpe", "char"]
character_coverage: 1.0

# Feature parameters (FBANKS etc)
sample_rate: 16000
n_fft: 400
n_mels: 80 

# Model parameters
activation: !name:torch.nn.LeakyReLU
dropout: 0.5
dnn_neurons: 500
dec_neurons: 500

#encoder with w2v
enc_dnn_layers: 1
enc_dnn_neurons: 80

# Outputs
output_neurons: 52 

# Decoding parameters
# Be sure that the bos and eos index match with the BPEs ones
blank_index: 0
beam_size: 20
temperature: 1.50

#
# Functions and classes
#
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

compute_features: !new:speechbrain.lobes.features.Fbank
    sample_rate: !ref <sample_rate>
    n_fft: !ref <n_fft>
    n_mels: !ref <n_mels>
#    f_min: !ref <f_min>


wav2vec2: !new:speechbrain.lobes.models.huggingface_wav2vec.HuggingFaceWav2Vec2
    source: !ref <wav2vec2_hub>
    output_norm: True
    freeze: False
    save_path: !ref <save_folder>/wav2vec2_checkpoint


enc2: !new:speechbrain.lobes.models.CRDNN.CRDNN
    input_shape: [null, null, 80]
    activation: !ref <activation>
    dropout: 0.15
    cnn_blocks: 0
    rnn_class: !name:speechbrain.nnet.RNN.LSTM
    rnn_layers: 5
    rnn_neurons: 512
    rnn_bidirectional: True
    rnn_re_init: True
    dnn_blocks: 2
    dnn_neurons: 1024

enc3: !new:speechbrain.lobes.models.CRDNN.CRDNN
    input_shape: [null, null, 1024] 
    activation: !ref <activation>
    dropout: 0.15
    cnn_blocks: 0
    rnn_class: !name:speechbrain.nnet.RNN.LSTM
    rnn_layers: 5
    rnn_neurons: 512 
    rnn_bidirectional: True
    rnn_re_init: True
    dnn_blocks: 2
    dnn_neurons: 1024

ctc_lin: !new:speechbrain.nnet.linear.Linear
    input_size: 1024 
    n_neurons: !ref <output_neurons>
    bias: True

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

modules:
    wav2vec2: !ref <wav2vec2>
    enc2: !ref <enc2>
    enc3: !ref <enc3>
    ctc_lin: !ref <ctc_lin>

model: !new:torch.nn.ModuleList
    - [!ref <ctc_lin>, !ref <enc2>, !ref <enc3>]

adam_opt_class: !name:torch.optim.Adam
    lr: !ref <lr>
 
wav2vec_opt_class: !name:torch.optim.Adam
    lr: !ref <lr_wav2vec>

ctc_cost: !name:speechbrain.nnet.losses.ctc_loss
    blank_index: !ref <blank_index>

lr_annealing_adam: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: 0.0025
    annealing_factor: 0.8
    patient: 0
 
lr_annealing_wav2vec: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr_wav2vec>
    improvement_threshold: 0.0025
    annealing_factor: 0.9

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        wav2vec2: !ref <wav2vec2>
        lr_annealing_adam: !ref <lr_annealing_adam>
        lr_annealing_wav2vec: !ref <lr_annealing_wav2vec>
        counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>


ctc_computer: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.ctc_loss
        blank_index: !ref <blank_index>
        reduction: batch


error_rate_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
    merge_tokens: True

coer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
    extract_concepts_values: True
    keep_values: False

cver_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
    extract_concepts_values: True
    keep_values: True

